/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.ExportDAO;
import DAO.ImportDAO;
import DAO.MemoryDAO;
import DAO.PhoneNameDAO;
import DAO.ProducerDAO;
import DAO.ProductDAO;
import DAO.SupplierDAO;
import DAO.TypeDAO;
import Helper.Helper;
import Model.Export;
import Model.Import;
import Model.Memory;
import Model.PhoneName;
import Model.Producer;
import Model.Product;
import Model.Type;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ma-user
 */
public class TK extends javax.swing.JPanel {

    public static int tab;
    private boolean tabLoaded;

    /**
     * Creates new form M
     */
    public TK() {
        this(1);
    }

    public TK(int tab) {
        tabLoaded = false;
        initComponents();
        this.tab = tab;
        loadTab(tab);
        tabLoaded = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpTK = new javax.swing.JTabbedPane();
        jtpTN = new javax.swing.JTabbedPane();
        jpnNK = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMHDN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jdtFromN = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtNCCN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jdtToN = new com.toedter.calendar.JDateChooser();
        btnTN = new javax.swing.JButton();
        btnRN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblN = new javax.swing.JTable();
        btnHomeN = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnBackN = new javax.swing.JButton();
        lblPosN = new javax.swing.JLabel();
        btnNextN = new javax.swing.JButton();
        btnEndN = new javax.swing.JButton();
        txtPosN = new javax.swing.JTextField();
        btnGoN = new javax.swing.JButton();
        btnXCTN = new javax.swing.JButton();
        jpnXK = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMHDX = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jdtFromX = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jdtToX = new com.toedter.calendar.JDateChooser();
        btnTX = new javax.swing.JButton();
        btnRX = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblX = new javax.swing.JTable();
        btnHomeX = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnBackX = new javax.swing.JButton();
        lblPosX = new javax.swing.JLabel();
        btnNextX = new javax.swing.JButton();
        btnEndX = new javax.swing.JButton();
        txtPosX = new javax.swing.JTextField();
        btnGoX = new javax.swing.JButton();
        btnXCTX = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtMHDSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnTSP = new javax.swing.JButton();
        btnRSP = new javax.swing.JButton();
        cboTH = new javax.swing.JComboBox<>();
        cboRam = new javax.swing.JComboBox<>();
        cboRom = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cboTM = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        btnHomeSP = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnBackSP = new javax.swing.JButton();
        lblPosSP = new javax.swing.JLabel();
        btnNextSP = new javax.swing.JButton();
        btnEndSP = new javax.swing.JButton();
        txtPosSP = new javax.swing.JTextField();
        btnGoSP = new javax.swing.JButton();
        btnXCTSP = new javax.swing.JButton();

        jtpTK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtpTKStateChanged(evt);
            }
        });

        jtpTN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtpTNStateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Mã hóa đơn:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Thời gian:      Từ:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Nhà cung cấp:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Đến:");

        btnTN.setText("Tìm");
        btnTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTNActionPerformed(evt);
            }
        });

        btnRN.setText("Reset");
        btnRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNCCN, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdtFromN, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdtToN, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdtFromN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMHDN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdtToN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNCCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn"));

        tblN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Nhà cung cấp", "Ngày nhập", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblN);

        btnHomeN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/home.png"))); // NOI18N
        btnHomeN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeNActionPerformed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Trang:");

        btnBackN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/back.png"))); // NOI18N
        btnBackN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackNActionPerformed(evt);
            }
        });

        lblPosN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPosN.setForeground(new java.awt.Color(255, 0, 51));
        lblPosN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosN.setText("1/1");

        btnNextN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/Next.png"))); // NOI18N
        btnNextN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextNActionPerformed(evt);
            }
        });

        btnEndN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/end.png"))); // NOI18N
        btnEndN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndNActionPerformed(evt);
            }
        });

        txtPosN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPosN.setText("1");

        btnGoN.setText("Đi đến");
        btnGoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoNActionPerformed(evt);
            }
        });

        btnXCTN.setText("Xem chi tiết");
        btnXCTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXCTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHomeN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBackN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPosN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNextN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEndN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPosN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGoN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXCTN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPosN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPosN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXCTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHomeN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBackN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNextN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEndN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGoN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnNKLayout = new javax.swing.GroupLayout(jpnNK);
        jpnNK.setLayout(jpnNKLayout);
        jpnNKLayout.setHorizontalGroup(
            jpnNKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnNKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnNKLayout.setVerticalGroup(
            jpnNKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpTN.addTab("Tìm hóa đơn nhập", jpnNK);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Mã hóa đơn:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Thời gian:      Từ:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Đến:");

        btnTX.setText("Tìm");
        btnTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTXActionPerformed(evt);
            }
        });

        btnRX.setText("Reset");
        btnRX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jdtFromX, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdtToX, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMHDX))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTX, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRX, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMHDX, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdtToX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdtFromX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn"));

        tblX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã hóa đơn", "Ngày xuất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblX);

        btnHomeX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/home.png"))); // NOI18N
        btnHomeX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeXActionPerformed(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Trang:");

        btnBackX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/back.png"))); // NOI18N
        btnBackX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackXActionPerformed(evt);
            }
        });

        lblPosX.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPosX.setForeground(new java.awt.Color(255, 0, 51));
        lblPosX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosX.setText("1/1");

        btnNextX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/Next.png"))); // NOI18N
        btnNextX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextXActionPerformed(evt);
            }
        });

        btnEndX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/end.png"))); // NOI18N
        btnEndX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndXActionPerformed(evt);
            }
        });

        txtPosX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPosX.setText("1");

        btnGoX.setText("Đi đến");
        btnGoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoXActionPerformed(evt);
            }
        });

        btnXCTX.setText("Xem chi tiết");
        btnXCTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXCTXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHomeX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBackX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNextX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEndX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGoX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXCTX, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPosX, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPosX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXCTX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHomeX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBackX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNextX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEndX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGoX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnXKLayout = new javax.swing.GroupLayout(jpnXK);
        jpnXK.setLayout(jpnXKLayout);
        jpnXKLayout.setHorizontalGroup(
            jpnXKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnXKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnXKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnXKLayout.setVerticalGroup(
            jpnXKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnXKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpTN.addTab("Tìm hóa đơn xuất", jpnXK);

        jtpTK.addTab("Tìm hóa đơn", jtpTN);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Mã hóa đơn:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Thương hiệu:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Ram:");

        btnTSP.setText("Tìm");
        btnTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSPActionPerformed(evt);
            }
        });

        btnRSP.setText("Reset");
        btnRSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSPActionPerformed(evt);
            }
        });

        cboTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboRom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Bộ nhớ:");

        cboTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Tên máy");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMHDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cboTM, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboRom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cboTH, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboRam, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRSP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMHDSP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRSP))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboRom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách điện thoại"));

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã điện thoại", "Tên điện thoại", "Số lượng trong kho", "Ngày bán gần nhất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSP);

        btnHomeSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/home.png"))); // NOI18N
        btnHomeSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeSPActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Trang:");

        btnBackSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/back.png"))); // NOI18N
        btnBackSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSPActionPerformed(evt);
            }
        });

        lblPosSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPosSP.setForeground(new java.awt.Color(255, 0, 51));
        lblPosSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosSP.setText("1/1");

        btnNextSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/Next.png"))); // NOI18N
        btnNextSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextSPActionPerformed(evt);
            }
        });

        btnEndSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/end.png"))); // NOI18N
        btnEndSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndSPActionPerformed(evt);
            }
        });

        txtPosSP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPosSP.setText("1");

        btnGoSP.setText("Đi đến");
        btnGoSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoSPActionPerformed(evt);
            }
        });

        btnXCTSP.setText("Xem chi tiết");
        btnXCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXCTSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHomeSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBackSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPosSP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNextSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEndSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPosSP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGoSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXCTSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPosSP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHomeSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEndSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPosSP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpTK.addTab("Tìm sản phẩm", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpTK)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpTK)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTNActionPerformed
        // TODO add your handling code here:
        int lenBefor, lenAfter;
        String f = txtNCCN.getText().trim();
        do {
            lenBefor = f.length();
            f = f.replaceAll("  ", " ");
            lenAfter = f.length();
        } while (lenBefor != lenAfter);
        lstNK = importDAO.getList(txtMHDN.getText().trim().equals("") ? null : txtMHDN.getText().trim(), f, jdtFromN.getDate(),
                Date.from((jdtToN.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().plusDays(1)).atStartOfDay().atZone(ZoneId.systemDefault()).toInstant()));
        curPageN = 1;
        fillTableNK();
    }//GEN-LAST:event_btnTNActionPerformed

    private void btnRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRNActionPerformed
        // TODO add your handling code here:
        txtMHDN.setText("");
        txtNCCN.setText("");
        lstNK = importDAO.getList();
        curPageN = 1;
        fillTableNK();
    }//GEN-LAST:event_btnRNActionPerformed

    private void tblNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNMouseClicked
        // TODO add your handling code here:
        rowN = tblN.getSelectedRow();
        if (rowN >= 0) {
            showN = (curPageN - 1) * itemPerPageN + rowN;
            btnXCTN.setText(lstNK.get(showN).getIm_stat().equals("TM") ? "Chỉnh sửa" : "Xem chi tiết");
        }
    }//GEN-LAST:event_tblNMouseClicked

    private void btnHomeNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeNActionPerformed
        // TODO add your handling code here:
        curPageN = 1;
        fillTableNK();
    }//GEN-LAST:event_btnHomeNActionPerformed

    private void btnBackNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackNActionPerformed
        // TODO add your handling code here:
        curPageN = curPageN > 1 ? curPageN - 1 : 1;
        fillTableNK();
    }//GEN-LAST:event_btnBackNActionPerformed

    private void btnNextNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextNActionPerformed
        // TODO add your handling code here:
        curPageN = curPageN < pageN ? curPageN + 1 : pageN;
        fillTableNK();
    }//GEN-LAST:event_btnNextNActionPerformed

    private void btnEndNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndNActionPerformed
        // TODO add your handling code here:
        curPageN = pageN;
        fillTableNK();
    }//GEN-LAST:event_btnEndNActionPerformed

    private void btnGoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoNActionPerformed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtPosN.getText()) != curPageN
                    && Integer.parseInt(txtPosN.getText()) > 0
                    && Integer.parseInt(txtPosN.getText()) <= pageN) {
                curPageN = Integer.parseInt(txtPosN.getText());
                fillTableNK();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "số trang phải lả số nguyên lớn hơn 0 và nhỏ hơn tổng tất cả các trang");
        }
    }//GEN-LAST:event_btnGoNActionPerformed

    private void btnXCTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXCTNActionPerformed
        // TODO add your handling code here:
        if (showN >= 0) {
            JPanel m = new NK(lstNK.get(showN), lstNK.get(showN).getIm_stat().equals("TM") ? "E" : "V");
            Helper.showPanel(m);
        } else {
            JOptionPane.showMessageDialog(this, "Mời chọn hóa đơn để xem");
        }
    }//GEN-LAST:event_btnXCTNActionPerformed

    private void btnTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTXActionPerformed
        // TODO add your handling code here:
        lstXK = exportDAO.getList(txtMHDX.getText().trim().equals("") ? null : txtMHDX.getText().trim(), jdtFromX.getDate(),
                Date.from((jdtToX.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().plusDays(1)).atStartOfDay().atZone(ZoneId.systemDefault()).toInstant()));
        curPageX = 1;
        fillTableXK();
    }//GEN-LAST:event_btnTXActionPerformed

    private void btnRXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRXActionPerformed
        // TODO add your handling code here:
        txtMHDX.setText("");
        lstXK = exportDAO.getList();
        curPageX = 1;
        fillTableXK();
    }//GEN-LAST:event_btnRXActionPerformed

    private void tblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXMouseClicked
        // TODO add your handling code here:
        rowX = tblX.getSelectedRow();
        if (rowX >= 0) {
            showX = (curPageX - 1) * itemPerPageX + rowX;
        }
    }//GEN-LAST:event_tblXMouseClicked

    private void btnHomeXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeXActionPerformed
        // TODO add your handling code here:
        curPageX = 1;
        fillTableXK();
    }//GEN-LAST:event_btnHomeXActionPerformed

    private void btnBackXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackXActionPerformed
        // TODO add your handling code here:
        curPageX = curPageX > 1 ? curPageX - 1 : 1;
        fillTableXK();
    }//GEN-LAST:event_btnBackXActionPerformed

    private void btnNextXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextXActionPerformed
        // TODO add your handling code here:
        curPageX = curPageX < pageX ? curPageX + 1 : pageX;
        fillTableXK();
    }//GEN-LAST:event_btnNextXActionPerformed

    private void btnEndXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndXActionPerformed
        // TODO add your handling code here:
        curPageX = pageX;
        fillTableXK();
    }//GEN-LAST:event_btnEndXActionPerformed

    private void btnGoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoXActionPerformed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtPosX.getText()) != curPageX
                    && Integer.parseInt(txtPosX.getText()) > 0
                    && Integer.parseInt(txtPosX.getText()) <= pageX) {
                curPageX = Integer.parseInt(txtPosX.getText());
                fillTableNK();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "số trang phải lả số nguyên lớn hơn 0 và nhỏ hơn tổng tất cả các trang");
        }
    }//GEN-LAST:event_btnGoXActionPerformed

    private void btnXCTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXCTXActionPerformed
        // TODO add your handling code here:
        if (showX >= 0) {
            JPanel m = new XK(lstXK.get(showX));
            Helper.showPanel(m);
        } else {
            JOptionPane.showMessageDialog(this, "Mời chọn hóa đơn để xem");
        }
    }//GEN-LAST:event_btnXCTXActionPerformed

    private void jtpTKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtpTKStateChanged
        // TODO add your handling code here:
        if (!tabLoaded) {
            return;
        }
        int sel = jtpTK.getSelectedIndex();
        if (sel == 1) {
            tab = 3;
            loadTab(tab);
        }
    }//GEN-LAST:event_jtpTKStateChanged

    private void jtpTNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtpTNStateChanged
        // TODO add your handling code here:
        if (!tabLoaded) {
            return;
        }
        int sel = jtpTN.getSelectedIndex();
        this.tab = sel == 0 ? 1 : 2;
        loadTab(tab);
    }//GEN-LAST:event_jtpTNStateChanged

    private void btnTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTSPActionPerformed

    private void btnRSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRSPActionPerformed

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSPMouseClicked

    private void btnHomeSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeSPActionPerformed

    private void btnBackSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackSPActionPerformed

    private void btnNextSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextSPActionPerformed

    private void btnEndSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEndSPActionPerformed

    private void btnGoSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoSPActionPerformed

    private void btnXCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXCTSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXCTSPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackN;
    private javax.swing.JButton btnBackSP;
    private javax.swing.JButton btnBackX;
    private javax.swing.JButton btnEndN;
    private javax.swing.JButton btnEndSP;
    private javax.swing.JButton btnEndX;
    private javax.swing.JButton btnGoN;
    private javax.swing.JButton btnGoSP;
    private javax.swing.JButton btnGoX;
    private javax.swing.JButton btnHomeN;
    private javax.swing.JButton btnHomeSP;
    private javax.swing.JButton btnHomeX;
    private javax.swing.JButton btnNextN;
    private javax.swing.JButton btnNextSP;
    private javax.swing.JButton btnNextX;
    private javax.swing.JButton btnRN;
    private javax.swing.JButton btnRSP;
    private javax.swing.JButton btnRX;
    private javax.swing.JButton btnTN;
    private javax.swing.JButton btnTSP;
    private javax.swing.JButton btnTX;
    private javax.swing.JButton btnXCTN;
    private javax.swing.JButton btnXCTSP;
    private javax.swing.JButton btnXCTX;
    private javax.swing.JComboBox<String> cboRam;
    private javax.swing.JComboBox<String> cboRom;
    private javax.swing.JComboBox<String> cboTH;
    private javax.swing.JComboBox<String> cboTM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdtFromN;
    private com.toedter.calendar.JDateChooser jdtFromX;
    private com.toedter.calendar.JDateChooser jdtToN;
    private com.toedter.calendar.JDateChooser jdtToX;
    private javax.swing.JPanel jpnNK;
    private javax.swing.JPanel jpnXK;
    private javax.swing.JTabbedPane jtpTK;
    private javax.swing.JTabbedPane jtpTN;
    private javax.swing.JLabel lblPosN;
    private javax.swing.JLabel lblPosSP;
    private javax.swing.JLabel lblPosX;
    private javax.swing.JTable tblN;
    private javax.swing.JTable tblSP;
    private javax.swing.JTable tblX;
    private javax.swing.JTextField txtMHDN;
    private javax.swing.JTextField txtMHDSP;
    private javax.swing.JTextField txtMHDX;
    private javax.swing.JTextField txtNCCN;
    private javax.swing.JTextField txtPosN;
    private javax.swing.JTextField txtPosSP;
    private javax.swing.JTextField txtPosX;
    // End of variables declaration//GEN-END:variables

    private void loadTab(int tab) {
        switch (tab) {
            case 2:
                jtpTK.setSelectedIndex(0);
                jtpTN.setSelectedIndex(1);
                loadXKTab();
                break;
            case 1:
                jtpTK.setSelectedIndex(0);
                loadNKTab();
                break;
            default:
                jtpTK.setSelectedIndex(1);
                loadSPTab();
        }
    }

    /*
     * nhap kho
     */
    private ArrayList<Import> lstNK;
    private ImportDAO importDAO;
    private int pageN, itemPerPageN, rowN, showN;
    public static int curPageN;
    private DefaultTableModel nkModel;

    //
    private void loadNKTab() {
        importDAO = new ImportDAO();
        jdtFromN.getDateEditor().setEnabled(false);
        jdtToN.getDateEditor().setEnabled(false);
        jdtFromN.setDate(Date.from(LocalDate.now().minusMonths(1).atTime(LocalTime.now()).atZone(ZoneId.systemDefault()).toInstant()));
        jdtToN.setDate(Date.from(LocalDate.now().atTime(LocalTime.now()).atZone(ZoneId.systemDefault()).toInstant()));
        lstNK = importDAO.getList();
        itemPerPageN = 3;
        nkModel = (DefaultTableModel) tblN.getModel();
        fillTableNK();
    }

    private void fillTableNK() {
        pageN = (int) Math.ceil(lstNK.size() / (double) itemPerPageN);
        int start = curPageN * itemPerPageN - itemPerPageN, end = itemPerPageN * curPageN - 1;
        if (lstNK.size() - 1 < end) {
            end = lstNK.size() - 1;
        }
        nkModel.setRowCount(0);
        if (lstNK.size() > 0) {
            for (int i = start; i <= end; i++) {
                String tt;
                switch (lstNK.get(i).getIm_stat()) {
                    case "TM":
                        tt = "Chờ hàng về";
                        break;
                    case "NDH":
                        tt = "Đã kiểm hàng";
                        break;
                    default:
                        tt = "Nhập kho xong";
                }
                nkModel.addRow(new Object[]{
                    lstNK.get(i).getIm_id(),
                    new SupplierDAO().select(lstNK.get(i).getSup_id()).getSup_name(),
                    new SimpleDateFormat("MMM dd, yyyy").format(lstNK.get(i).getIm_date()),
                    tt});
            }
            lblPosN.setText(String.valueOf(curPageN) + "/" + String.valueOf(pageN));
            txtPosN.setText(String.valueOf(curPageN));
        } else {
            lblPosN.setText("");
            txtPosN.setText("");
        }
        nkModel.fireTableDataChanged();
        rowN = -1;
        showN = -1;
    }

    /*
     * xuat kho
     */
    private ArrayList<Export> lstXK;
    private ExportDAO exportDAO;
    private int pageX, itemPerPageX, rowX, showX;
    public static int curPageX;
    private DefaultTableModel xkModel;

    //
    private void loadXKTab() {
        exportDAO = new ExportDAO();
        jdtFromX.getDateEditor().setEnabled(false);
        jdtToX.getDateEditor().setEnabled(false);
        jdtFromX.setDate(Date.from(LocalDate.now().minusMonths(1).atTime(LocalTime.now()).atZone(ZoneId.systemDefault()).toInstant()));
        jdtToX.setDate(Date.from(LocalDate.now().atTime(LocalTime.now()).atZone(ZoneId.systemDefault()).toInstant()));
        lstXK = exportDAO.getList();
        itemPerPageX = 3;
        xkModel = (DefaultTableModel) tblX.getModel();
        fillTableXK();
    }

    private void fillTableXK() {
        pageX = (int) Math.ceil(lstXK.size() / (double) itemPerPageX);
        int start = itemPerPageX * curPageX - itemPerPageX, end = itemPerPageX * curPageX - 1;
        if (lstXK.size() - 1 < end) {
            end = lstXK.size() - 1;
        }
        xkModel.setRowCount(0);
        if (lstXK.size() > 0) {
            for (int i = start; i <= end; i++) {
                xkModel.addRow(new Object[]{
                    lstXK.get(i).getEx_id(),
                    new SimpleDateFormat("MMM dd, yyyy - hh:mm a").format(lstXK.get(i).getEx_date())});
            }
            lblPosX.setText(String.valueOf(curPageX) + "/" + String.valueOf(pageX));
            txtPosX.setText(String.valueOf(curPageX));
        } else {
            lblPosX.setText("");
            txtPosX.setText("");
        }
        xkModel.fireTableDataChanged();
    }

    /*
     * san pham
     */
    private ArrayList<Producer> lstSPTH;
    private ArrayList<PhoneName> lstSPTM;
    private ArrayList<Memory> lstSPBN;
    private ArrayList<Type> lstSP;
    private TypeDAO typeDAO;
    private ProductDAO productDAO;
    private ProducerDAO producerDAO;
    private PhoneNameDAO phoneNameDAO;
    private MemoryDAO memoryDAO;
    private int pageSP, itemPerPageSP, rowSP, showSP, curPageSP;
    private DefaultTableModel spModel;
    private DefaultComboBoxModel thModel, tmModel, ramModel, romModel;

    //
    private void loadSPTab() {
        productDAO = new ProductDAO();
        typeDAO = new TypeDAO();
        lstSP = typeDAO.selectAll(false);
        itemPerPageSP = 3;
        spModel = (DefaultTableModel) tblSP.getModel();
        loadTH();
        loadBN();

    }

    private void loadTH() {
        producerDAO = new ProducerDAO();
        lstSPTH = producerDAO.selectAll();
        thModel = new DefaultComboBoxModel();
        cboTH.setModel(thModel);
        thModel.removeAllElements();
        thModel.addElement("-");
        for (Producer producer : lstSPTH) {
            thModel.addElement(producer);
        }
        loadTM();
    }

    private void loadTM() {
        int sel = cboTM.getSelectedIndex();
        phoneNameDAO = new PhoneNameDAO();
        tmModel = new DefaultComboBoxModel();
        cboTM.setModel(tmModel);
        tmModel.removeAllElements();
        tmModel.addElement("-");
        if (sel > 0) {
            lstSPTM = phoneNameDAO.selectAllByColumn(lstSPTH.get(sel - 1).getId());
            for (PhoneName phoneName : lstSPTM) {
                tmModel.addElement(phoneName);
            }
        }
    }

    private void loadBN() {
        memoryDAO = new MemoryDAO();
        lstSPBN = memoryDAO.selectAll();
        ramModel = new DefaultComboBoxModel();
        romModel = new DefaultComboBoxModel();
        cboRam.setModel(ramModel);
        cboRom.setModel(romModel);
        ramModel.removeAllElements();
        romModel.removeAllElements();
        romModel.addElement("-");
        ramModel.addElement("-");
        for (Memory memory : lstSPBN) {
            ramModel.addElement(memory);
            romModel.addElement(memory);
        }
    }
}
