/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Helper.Helper;
import Model.Account;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ma-user
 */
public class Main extends javax.swing.JFrame {

    public static Account account;
    public static boolean logged = false;
    public Thread t1 = new Thread(new Runnable() {
        @Override
        public void run() {
            while (true) {
                if (logged == false) {
                    showLG();
                }
            }
        }
    });

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
//        setSize(new Dimension(1366, 800));
        if (Helper.openConnection() == false) {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi. Xin mời chạy lại.");
        }
        t1.start();
        settime();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnMain = new javax.swing.JToggleButton();
        btnNK = new javax.swing.JToggleButton();
        btnXK = new javax.swing.JToggleButton();
        btnNCC = new javax.swing.JToggleButton();
        btnMSP = new javax.swing.JToggleButton();
        btnQLK = new javax.swing.JToggleButton();
        btnTK = new javax.swing.JToggleButton();
        btnTDTT = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        rootP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ XUẤT NHẬP KHO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(btnMain);
        btnMain.setText("CHƯƠNG TRÌNH");
        btnMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnMainStateChanged(evt);
            }
        });
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnNK);
        btnNK.setText("NHẬP KHO");
        btnNK.setEnabled(false);
        btnNK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnNKStateChanged(evt);
            }
        });

        buttonGroup1.add(btnXK);
        btnXK.setText("XUẤT KHO");
        btnXK.setEnabled(false);
        btnXK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnXKStateChanged(evt);
            }
        });

        buttonGroup1.add(btnNCC);
        btnNCC.setText("NHÀ CUNG CẤP");
        btnNCC.setEnabled(false);
        btnNCC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnNCCStateChanged(evt);
            }
        });

        buttonGroup1.add(btnMSP);
        btnMSP.setText("MÃ SẢN PHẨM");
        btnMSP.setEnabled(false);
        btnMSP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnMSPStateChanged(evt);
            }
        });

        buttonGroup1.add(btnQLK);
        btnQLK.setText("QUẢN LÝ KỆ");
        btnQLK.setEnabled(false);
        btnQLK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnQLKStateChanged(evt);
            }
        });

        buttonGroup1.add(btnTK);
        btnTK.setText("TÌM KIẾM");
        btnTK.setEnabled(false);
        btnTK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnTKStateChanged(evt);
            }
        });

        buttonGroup1.add(btnTDTT);
        btnTDTT.setText("THAY ĐỔI TRẠNG THÁI");
        btnTDTT.setEnabled(false);
        btnTDTT.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnTDTTStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTDTT, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMain)
                .addGap(18, 18, 18)
                .addComponent(btnNK)
                .addGap(18, 18, 18)
                .addComponent(btnXK)
                .addGap(18, 18, 18)
                .addComponent(btnNCC)
                .addGap(18, 18, 18)
                .addComponent(btnMSP)
                .addGap(18, 18, 18)
                .addComponent(btnQLK)
                .addGap(18, 18, 18)
                .addComponent(btnTK)
                .addGap(18, 18, 18)
                .addComponent(btnTDTT)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblUser.setText("Admin");

        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTime.setText("Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 744, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 741, 1368, -1));

        javax.swing.GroupLayout rootPLayout = new javax.swing.GroupLayout(rootP);
        rootP.setLayout(rootPLayout);
        rootPLayout.setHorizontalGroup(
            rootPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1144, Short.MAX_VALUE)
        );
        rootPLayout.setVerticalGroup(
            rootPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        getContentPane().add(rootP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1144, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMainActionPerformed

    private void btnMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnMainStateChanged
        // TODO add your handling code here:
        if (btnMain.isSelected()) {
            M m = new M();
            showPanel(m);
        }
    }//GEN-LAST:event_btnMainStateChanged

    private void btnNKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnNKStateChanged
        // TODO add your handling code here:
        if (btnNK.isSelected()) {
            NK m = new NK();
            showPanel(m);
        }
    }//GEN-LAST:event_btnNKStateChanged

    private void btnXKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnXKStateChanged
        // TODO add your handling code here:
        if (btnXK.isSelected()) {
            XK m = new XK();
            showPanel(m);
        }
    }//GEN-LAST:event_btnXKStateChanged

    private void btnNCCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnNCCStateChanged
        // TODO add your handling code here:
        if (btnNCC.isSelected()) {
            NCC m = new NCC();
            showPanel(m);
        }
    }//GEN-LAST:event_btnNCCStateChanged

    private void btnMSPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnMSPStateChanged
        // TODO add your handling code here:
        if (btnMSP.isSelected()) {
            MSP m = new MSP();
            showPanel(m);
        }
    }//GEN-LAST:event_btnMSPStateChanged

    private void btnQLKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnQLKStateChanged
        // TODO add your handling code here:
        if (btnQLK.isSelected()) {
            QLK m = new QLK();
            showPanel(m);
        }
    }//GEN-LAST:event_btnQLKStateChanged

    private void btnTKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnTKStateChanged
        // TODO add your handling code here:
        if (btnTK.isSelected()) {
            TK m = new TK();
            showPanel(m);
        }
    }//GEN-LAST:event_btnTKStateChanged

    private void btnTDTTStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnTDTTStateChanged
        // TODO add your handling code here:
        if (btnTDTT.isSelected()) {
            TDTT m = new TDTT();
            showPanel(m);
        }
    }//GEN-LAST:event_btnTDTTStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMSP;
    private javax.swing.JToggleButton btnMain;
    private javax.swing.JToggleButton btnNCC;
    private javax.swing.JToggleButton btnNK;
    private javax.swing.JToggleButton btnQLK;
    private javax.swing.JToggleButton btnTDTT;
    private javax.swing.JToggleButton btnTK;
    private javax.swing.JToggleButton btnXK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel rootP;
    // End of variables declaration//GEN-END:variables

    private void settime() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    SimpleDateFormat sdf = new SimpleDateFormat("MMM dd yyyy - hh:mm:ss");
                    lblTime.setText(sdf.format(Date.from(LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant())));
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        });
        t.start();
    }

    public void showLG() {
        Login lg = new Login(this, true);
        lg.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent we) {
                if (logged == false) {
                    System.exit(0);
                }
                setMenuState(logged);
                btnMain.setSelected(true);
            }
        });
        lg.setVisible(true);
    }

    private void setMenuState(boolean logged) {
        btnNK.setEnabled(logged);
        btnXK.setEnabled(logged);
        btnNCC.setEnabled(logged && account.getRole().equalsIgnoreCase("QL"));
        btnMSP.setEnabled(logged && account.getRole().equalsIgnoreCase("QL"));
        btnQLK.setEnabled(logged && account.getRole().equalsIgnoreCase("QL"));
        btnTK.setEnabled(logged);
        btnTDTT.setEnabled(logged);
        lblUser.setText(logged ? account.getUser() : "");
    }

    private void showPanel(JPanel panel) {
        rootP.removeAll();
        javax.swing.GroupLayout rootPLayout = new javax.swing.GroupLayout(rootP);
        rootP.setLayout(rootPLayout);
        rootPLayout.setHorizontalGroup(
                rootPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel)
        );
        rootPLayout.setVerticalGroup(
                rootPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel)
        );
    }

}
